export const FAST_CHARTING_MIN_WIDTH = 200;
export const FAST_CHARTING_MIN_HEIGHT = 150;
export const FAST_CHARTING_DEFAULT_WIDTH = 400;
export const FAST_CHARTING_DEFAULT_HEIGHT = 300;
export const FAST_CHARTING_RESIZE_HANDLE_SIZE = 16;
export const FAST_CHARTING_EXPANDED_WIDTH_PERCENT = 20;
export const FAST_CHARTING_COLLAPSED_WIDTH = 40;
